language: rust

dist: xenial

env:
  global:
  - RUST_BACKTRACE=full
  - TARGET=x86_64-unknown-linux-gnu

rust:
- stable
- beta

before_script:
- rustup component add rustfmt

script:
- python -V
- python3 -V
- cargo fmt --all -- --check
- cargo build --verbose
- cargo test --verbose
- cargo build --release --target $TARGET
- ls -lh target/$TARGET/release/
