language: rust

dist: xenial

env:
  global:
  - RUST_BACKTRACE=full
  - TARGET=x86_64-unknown-linux-gnu

rust:
- stable
- beta

before_script:
- rustup component add rustfmt
- curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
- python3 get-pip.py --user
- python3 -m pip install pytest pytest-sugar

script:
- cargo fmt --all -- --check
- cargo build --verbose
- python3 -m pytest tests/
- cargo build --release --target $TARGET
- ls -lh target/$TARGET/release/
